{% set name = "Naked" %}
{% set version = "0.1.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Naked-{{ version }}.tar.gz
  sha256: f81015107e3aefdc801d7144fbae214bdf3cb179c0020a1dc6d5acb3659d5d5c

build:
  entry_points:
    - naked = Naked.app:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests
    - pyyaml

test:
  imports:
    - Naked
  commands:
    - pip check
    - naked --help
  requires:
    - pip

about:
  home: https://github.com/chrissimpkins/naked
  summary: A command line application framework
  license: Apache-2.0
  license_file: lib/Naked/templates/licenses.py

extra:
  recipe-maintainers:
    - millsks
